### ISSUE TITLE
An issue during installing process 

### ISSUE THREAD

**Issue by rebarhama** [peter-tharwat/dashboard#1]
Illuminate\Database\QueryException

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dashboard.settings' doesn't exist (SQL: select * from `settings` limit 1)

  at C:\xampp\htdocs\dashboard\vendor\laravel\framework\src\Illuminate\Database\Connection.php:703
    699▕         // If an exception occurs when attempting to run a query, we'll format the error
    700▕         // message to include the bindings with SQL, which will make this exception a
    701▕         // lot more helpful to the developer instead of just the database's errors.
    702▕         catch (Exception $e) {
  ➜ 703▕             throw new QueryException(
    704▕                 $query, $this->prepareBindings($bindings), $e
    705▕             );
    706▕         }
    707▕     }

**Comment by peter-tharwat** [comment]
Solved : You have to run 

```php
php artisan db:seed
```

### How to setup

```php
# after connect your database via .env file 
php artisan migrate:fresh
php artisan db:seed
```

### Credentials

```php
login page : http://127.0.0.1:8000/login
email : admin@admin.com
password : password
```

**Comment by rebarhama** [comment]
Dear Mr.Peter,
Thanks for your clarification,
I did it, but still not working the same issue showed .

![red](https://user-images.githubusercontent.com/15612061/141992212-9c03fb9c-8be3-4108-8080-e3ca39cd8587.PNG)
