### ISSUE TITLE
error when open contact page

### ISSUE THREAD

**Issue by RedaKassoumehDev** [peter-tharwat/dashboard#21]
App\Models\Setting::phone must return a relationship instance.

[screencapture-127-0-0-1-8000-contact-2022-12-19-21_45_02.pdf](https://github.com/peter-tharwat/dashboard/files/10261894/screencapture-127-0-0-1-8000-contact-2022-12-19-21_45_02.pdf)

**Comment by abdelmjid-saber** [comment]
تم حل المشكلة في اخر تحديث

**Comment by abdelmjid-saber** [comment]
> App\Models\Setting::phone must return a relationship instance.
> 
> [screencapture-127-0-0-1-8000-contact-2022-12-19-21_45_02.pdf](https://github.com/peter-tharwat/dashboard/files/10261894/screencapture-127-0-0-1-8000-contact-2022-12-19-21_45_02.pdf)

تم حل المشكلة في اخر تحديث

**Comment by peter-tharwat** [comment]
Nice Notes , thanks
