### ISSUE TITLE
 when upload logo getting this error

### ISSUE THREAD

**Issue by husseinsaleh22** [peter-tharwat/dashboard#22]
![Screenshot_20230122-151326](https://user-images.githubusercontent.com/76610276/213917711-cbef37da-26e5-4293-998a-f216b017e445.jpg)

**Comment by husseinsaleh22** [comment]
https://flareapp.io/share/x7K3DvZ7#F75

**Comment by husseinsaleh22** [comment]
?????

**Comment by momar3632** [comment]
ده عاوز صلاحيات من استضافة عندك ذات نفسها انه يقدر يكريت فولدر

**Comment by momar3632** [comment]
ظبط صلاحيات وهيشتغل معاك

**Comment by husseinsaleh22** [comment]
من وين بظبط اي ملف يحتاح صلاحية

**Comment by peter-tharwat** [comment]
please ensure that you have the permissions to create new folders inside storage folder
