### ISSUE TITLE
There is a problem with the latest update

### ISSUE THREAD

**Issue by momar3632** [peter-tharwat/dashboard#23]
toastr and jquery and favico

not working 

i try this

npm i 
npm run build 

and this 
include(F:\xampp\htdocs\dashboard-peter\vendor\composer/../../app/View/Components/Notifications.php): Failed to open stream: No such file or directory 

but not working  ?!

**Comment by momar3632** [comment]
لوحة مليانه مشاكل حتى اشعارات لحظية مش شغال من ساعت تحديث اخير اعتقد ليه علاقة بملفات js و css علشان خلتهم في npm في حاجه غلط اتمنا رد

**Comment by peter-tharwat** [comment]
please make sure that you have right directories permission , use npm run prod insread
