### ISSUE TITLE
Can you add a new feature?

### ISSUE THREAD

**Issue by momar3632** [peter-tharwat/dashboard#24]
The user's photo will be changed to a new one, so I see no need to keep the old one. How do I delete old photos when a user changes their profile picture

And you can also add it, and the same thing when I delete a user from admin, delete his picture, and the same thing with the rest, such as articles, categories, ....

I think it will be better and will save space on the server

**Comment by peter-tharwat** [comment]
you can override function for removing old photo, currently we dont need it
