### ISSUE TITLE
Class 'Imagick' not found

### ISSUE THREAD

**Issue by mahmoud-saber125** [peter-tharwat/dashboard#3]
When I select the images and press save, this error appears. Please is there a solution?
![Screenshot_2](https://user-images.githubusercontent.com/94830640/142831641-fdfce3a4-f661-4b2d-b04a-746fa12cb76c.png)

**Comment by peter-tharwat** [comment]
Dont forget to install and enable Imagick php extension
if you are using ubuntu , mint ...
`sudo apt install php-imagick`
