### ISSUE TITLE
Found Virus In The Files

### ISSUE THREAD

**Issue by Mohamed-Mohsen2021** [peter-tharwat/dashboard#4]
Hello Peter Thanks for your hard work,
Kindly be informed that when i try to download the resources i found a virus 
can you please check this ?

**Comment by peter-tharwat** [comment]
Can you share it please ?

**Comment by Mohamed-Mohsen2021** [comment]
![image](https://user-images.githubusercontent.com/77060386/151534582-61b91a87-a0e5-46c7-b20d-9140405bbe5a.png)

Check please

**Comment by peter-tharwat** [comment]
File removed,
please check again and let me know if any alert appears

**Comment by Mohamed-Mohsen2021** [comment]
Solved ,
Thanks Peter for this hard work
