### ISSUE TITLE
Class "Imagick" not found

### ISSUE THREAD

**Issue by Ammar777** [peter-tharwat/dashboard#6]
when i try to add a new user or modify. how i can fix it.

![screencapture-localhost-dashboard-master-public-admin-profile-update-2022-05-22-00_24_54](https://user-images.githubusercontent.com/18471073/169669511-d737c503-03b4-4216-9c3e-09228512505f.png)

**Comment by Raed-IT** [comment]
and me

**Comment by Raed-IT** [comment]
![image](https://user-images.githubusercontent.com/101429551/198895744-1252c511-d9c8-4bee-b5af-b24cd7ea316a.png)

im find the selution only install the imagick 




the step [https://ourcodeworld.com/articles/read/349/how-to-install-and-enable-the-imagick-extension-in-xampp-for-windows](in )
